version: '3'
services:
  react-app:
    build: .
    image: react-app
    ports:
      - "3000:3000"
    networks:
      - my-network

  backend:
    build: ./backend
    image: node-api
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge