
services:
  frontend:
    container_name: cd_front
    build: .

    ports:
      - "3000:3000"
    networks:
      - my-network

  backend:
    container_name: cd_back
    build: .
    ports:
      - "2000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge