
services:
  frontend:
    container_name: cd_front
    build: ./frontend

    ports:
      - "80:3000"
    networks:
      - my-network

  backend:
    container_name: cd_back
    build: ./backend
    ports:
      - "2000:3000"
    networks:
      - my-network

  grafana:
    image: grafana/grafana-oss
    container_name: grafana   
    ports:
     - "3000:3000"
    volumes: 
     - grafana-storage:/var/lib/grafana
    restart: always

  promethuse:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
     - 9091:9090  
    volumes:
     - ./prometheus:/etc/prometheus
    networks:
     - my-network


volumes:
  grafana-storage:
        

networks:
  my-network:
    driver: bridge