
services:
  frontend:
    container_name: cd_front
    build: ./frontend

    ports:
      - "80:3000"
    networks:
      - my-network

  backend:
    container_name: cd_back
    build: ./backend
    ports:
      - "2000:3000"
    networks:
      - my-network

  grafana:
    image: grafana/grafana-oss
    container_name: grafana   
    ports:
     - "3000:3000"
    volumes: 
      - grafana-storage :/var/lib/grafana
    restart: always

volumes:
  grafana-storage:
        

networks:
  my-network:
    driver: bridge